### ISSUE TITLE
The moonlander is not drawn when the moonlander is to far from the origin

### ISSUE THREAD

**Issue by dvberkel** [darwins-challenge/moonlander-visualisation#1]
Notably in early generated solutions, the moonlander seems to "dissapear". This is due to the fact that it gets out of reach of the drawing trio.

We should normalize the x coordinate when drawing.

**Comment by rix0rrr** [comment]
Should already be fixed in HEAD. I noticed that too :)

**Comment by rix0rrr** [comment]
Btw, we should probably meet up again. Any weekend that suits you?

**Comment by dvberkel** [comment]
The weekend of 24-25 September suits me. Does it suit you?
Or else 1-2 October.

I will reserve them, hoping that one of these is available for you as well

**Comment by rix0rrr** [comment]
24-25 is perfect

**Comment by dvberkel** [comment]
I will finalize that in my agenda.  Your place or mine? Scratch that, let's do it at your place, if we want a kids-free working zone

**Comment by dvberkel** [comment]
Other question, should I bring our rocket?

**Comment by rix0rrr** [comment]
Ours, and probably!
